version: '3'

services:
  mirror-maker:
    image: docker.io/bitnami/kafka:3.8.0-debian-12-r6
    hostname: mirror-maker
    container_name: mirror-maker
    volumes:
      - ./mm2_config:/tmp/kafka/config
    ports:
      - 9091:9091
      - 29096:29096
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_ZOOKEEPER_CONNECT: zookeeperA:2181,zookeeperB:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29096,PLAINTEXT_HOST://:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://mirror-maker:29096,PLAINTEXT_HOST://localhost:9091
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    restart: always